const loginFields = [
  {
    labelText: "Nume de utilizator",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    isRequired: true,
    placeholder: "Nume de utilizator",
  },
  {
    labelText: "Parola",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Parola",
  },
];

const signupFields = [
  {
    labelText: "Prenume",
    labelFor: "firstname",
    id: "firstName",
    name: "firstname",
    type: "text",
    autoComplete: "firstname",
    isRequired: true,
    placeholder: "Prenume",
  },
  {
    labelText: "Nume",
    labelFor: "lastname",
    id: "lastName",
    name: "lastname",
    type: "text",
    autoComplete: "lastname",
    isRequired: true,
    placeholder: "Nume",
  },
  {
    labelText: "Nume de utilizator",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Nume de utilizator",
  },
  {
    labelText: "Adresa de email",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Adresa de email",
  },
  {
    labelText: "Parola",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Parola",
  },
  {
    labelText: "Confirma parola",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirma parola",
  },
];

export { loginFields, signupFields };
